{
 "title": "RedisMonitor",
 "time": { "from": "2023-06-08T08:14:32.616Z", "to": "2023-06-08T08:24:02.334Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up, instance)"
    }
   },
   { "name": "interval", "query": "15s,30s,1m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "YCSB客户端监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "总QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(optName) (rate(optInvoke_seconds_count[$interval]))",
     "legendFormat": "总{{optName}}"
    }
   ]
  },
  {
   "title": "操作延迟",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(optName)(rate(optInvoke_seconds_sum[$interval]))/sum by(optName)(rate(optInvoke_seconds_count[$interval]))",
     "legendFormat": "avg-{{optName}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(optInvoke_seconds_bucket[$interval]))by (optName,le))",
     "legendFormat": "P50-{{optName}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(optInvoke_seconds_bucket[$interval]))by (optName,le))",
     "legendFormat": "P90-{{optName}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(optInvoke_seconds_bucket[$interval]))by (optName,le))",
     "legendFormat": "P95-{{optName}}"
    },
    { "expr": "optInvoke_seconds_max", "legendFormat": "max-{{optName}}" }
   ]
  },
  {
   "title": "Batch flat QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(optName) (rate(batchOptInvoke_total[$interval]))",
     "legendFormat": "{{optName}}"
    }
   ]
  },
  {
   "title": "平均Batch size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(optName) (rate(batchOptInvoke_total[$interval]))/sum by(optName) (rate(optInvoke_seconds_count[$interval]))",
     "legendFormat": "{{optName}}"
    }
   ]
  },
  { "title": "Redis服务端监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Redis connected clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "container cpu usage ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"redis\"}",
     "legendFormat": "containerId:{{id}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=~\"$instance\"} [$interval]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\"} ",
     "legendFormat": "max"
    }
   ]
  }
 ]
}