{
 "title": "YCSB-client",
 "time": { "from": "2023-05-18T07:33:00.801Z", "to": "2023-05-18T07:35:42.339Z" },
 "templating": {
  "list": [
   { "name": "interval", "query": "30s,1m,2m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(optInvoke_seconds_count[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "延迟",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(optInvoke_seconds_sum[$interval])/rate(optInvoke_seconds_count[$interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(optInvoke_seconds_bucket[$interval]))by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(optInvoke_seconds_bucket[$interval]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(optInvoke_seconds_bucket[$interval]))by (le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Batch flat QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(batchOptInvoke_total[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch size QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(batchOptInvoke_total[$interval])/rate(optInvoke_seconds_count[$interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}